[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "stmux"
version = "0.1.0"
description = "Simple Tmux Session Overview Tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual>=8.2.8",
]

[project.scripts]
stmux = "stmux.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.tcss"]
