[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "smux"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "textual>=8.2.8",
    "textual-tty>=0.4.0",
]

[project.scripts]
smux = "smux:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]
